export enum ServiceOrderStatus {
  RECEIVED = "RECEIVED",
  IN_DIAGNOSTIC = "IN_DIAGNOSTIC",
  AWAITING_APPROVAL = "AWAITING_APPROVAL",
  IN_EXECUTION = "IN_EXECUTION",
  COMPLETED = "COMPLETED",
  DELIVERED = "DELIVERED",
  CANCELED = "CANCELED",
}
