services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
      - /app/.bun
    environment:
      - APP_ENV=dev
      - DATABASE_URL=postgres://bun:bun@db:5432/bunzina
    depends_on:
      db:
        condition: service_healthy
    command: ['bun', 'run', 'start:with-migrations']
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: bunzina
      POSTGRES_USER: bun
      POSTGRES_PASSWORD: bun
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U bun -d bunzina']
      interval: 5s
      timeout: 5s
      retries: 5
  db_test:
    image: postgres:15
    environment:
      POSTGRES_DB: bunzina_test
      POSTGRES_USER: bun
      POSTGRES_PASSWORD: bun
    ports:
      - '5433:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U bun -d bunzina_test']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db-data: