version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/.bun

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: bunzina
      POSTGRES_USER: bun
      POSTGRES_PASSWORD: bun
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
