app-chart:
  app:
    secret:
      PROD_DB_USER: "bun"
      PROD_DB_PASSWORD: "CHANGE_ME"
      JWT_SECRET: "CHANGE_ME"
      API_KEY: "CHANGE_ME"
      EMAIL_SMTP_USER: ""
      EMAIL_SMTP_PASSWORD: ""
  database:
    secret:
      POSTGRES_USER: "bun"
      POSTGRES_PASSWORD: "CHANGE_ME"
      POSTGRES_DB: "bunzina"
